package com.oven.demo.core.base.utils;

import org.springframework.jdbc.core.PreparedStatementCreator;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class AutoGeneratePreparedStatementCreator implements PreparedStatementCreator {

    private final String sql;
    private final Object[] params;
    private final String autoGeneratedColumnName;

    public AutoGeneratePreparedStatementCreator(String sql, Object[] params, String autoGeneratedColumnName) {
        this.sql = sql;
        this.params = params;
        this.autoGeneratedColumnName = autoGeneratedColumnName;
    }

    @Override
    public PreparedStatement createPreparedStatement(Connection connection) throws SQLException {
        PreparedStatement ps = connection.prepareStatement(sql, new String[]{autoGeneratedColumnName});
        for (int i = 0; i < params.length; i++) {
            Object value = params[i];
            ps.setObject((i + 1), value);
        }
        return ps;
    }

}